
using UnityEngine;

public class KnifeController : MonoBehaviour
{
    [SerializeField] private Rigidbody[] _knives;
    [SerializeField] private AudioSource _audioSource;
    [SerializeField] private AudioClip _fallSound;
    
    public void DropKnives()
    {
        if (_audioSource != null && _fallSound != null)
        {
            _audioSource.PlayOneShot(_fallSound);
        }

        foreach (var knifeRb in _knives)
        {
            if (knifeRb != null)
            {
                knifeRb.isKinematic = false;
                knifeRb.useGravity = true;
            }
        }
            
        // Опционально: отключаем этот компонент, чтобы ножи не упали снова
        // enabled = false; 
    }
}