
using UnityEngine;
using UnityEngine.Events;

public class GameEventListener : MonoBehaviour
{
    [Tooltip("Событие, на которое нужно отреагировать.")]
    [SerializeField] private GameEvent _event;

    [Tooltip("Действия, которые выполнятся при срабатывании события.")]
    [SerializeField] private UnityEvent _response;

    private void OnEnable()
    {
        _event.RegisterListener(this);
    }

    private void OnDisable()
    {
        _event.UnregisterListener(this);
    }

    public void OnEventRaised()
    {
        _response.Invoke();
    }
}